[package]
name = "state_machine"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A State Machine Framework written in Rust."
repository = "https://github.com/DeCa09/state_machine"

[dependencies]