name: Rust CI

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: 'always'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        rust: [stable]

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - name: Install CI dependencies
      run: |
        cargo install cargo-audit
        cargo install --locked cargo-deny
    - name: Code Formatting Check
      run: cargo fmt --check
    - name: Dependency Security and Licensing Check
      run: |
        cargo audit
        cargo deny check
    - name: Code Compilation Check
      run: cargo check
    - name: Linting
      run: cargo clippy
    - name: Test
      run: cargo test
